varoworld: world
discord-id: 498457217754857482

sessions:
  length: 900
  per-week: 15
  day-limit: 4

start_protection: 60
login_protection: 10
min_logout_distance: 20

border:
  mode: EDGE
  shrink-time: 672
  radius: 5000
  end-radius: 250

coord-post:
- Friday, 14

friendlyfire:
  enabled: false
  allow-boost: true

spectate-allowed-if-team-alive: true
spawn-teams-together: true
allow-prevent-coordinate-post: false
default-hud: SCOREBOARD

disallowed-items:
  general:
    - GOLDEN_APPLE(1)
    - HOPPER_MINECART
  use-only:
    - EYE_OF_ENDER

potions:
  enabled: true
  splash-potions: false
  disabled-potions:
     - STRENGTH
     - INVISIBILITY
     - REGENERATION

plugin:
  running: false
  current_week: 0
  day: 0
  hours: 0